### ISSUE TITLE
Question about correct parameters

### ISSUE THREAD

**Issue by sagerio** [vegidio-docker/parse#1]
Hi,

at first, meryy christmas to you and thanks for the great work!

I'm posting this question because I couldn't find some "real world"-example and struggeling with running the container correctly:

`docker run --rm --network="host" -e SERVER_URL=http://localhost -e DB_URL=postgres://postgres:postgres@localhost:5432 -e MASTER_KEY=123456789 -e APP_IDS=app1,app2 -e DASHBOARD_USERNAME=admin -e DASHBOARD_PASSWORD=admin -p 80:80 --name vegidio-parse-server vegidio/parse`

What I'm unsure about is 

- the SERVER_URL: Docker is running on my home nas, so when I want to reach the parse server under the address http://nas:1337, which SERVER_URL I have to provide?
- As DB_URL I want to use a postgres installtion (no docker) on the nas system, so is it correct to provide '--network="host"' and 'localhost' for the postgres instance?
- How does the Port setting '-p' affect the whole thing when I also can pass a port with the SERVER_URL parameter?
- After starting, I got an error message "error: database 'parse_app1' does not exist" (although it does). I believe it has to do with the wrong DB_URL parameter so postgres cant be reached.
- The dashboard shows the error "couldn't connect to server" for both apps

I assume the root cause for all this are the wrong parameters for DB_URL and SERVER_URL (and perhaps port) I provide, perhaps someone could give me a hint how the parameters should be look like.

Thanks in advance,
Robert

**Comment by vegidio** [comment]
Hello and Merry Christmas! I will try to explain the parameters a little better:

`SERVER_URL` is the **external** URL that will be used to access your Parse Server. For example, if your Parse Server is hosted on a server that can be externally accessed by anyone through the domain `example.com` then the value of the `SERVER_URL` should be `http://example.com`. If your Parse Server is running in your own machine and you want to access it from the same machine then `SERVER_URL` will probably be `http://localhost`.

The port in the `SERVER_URL` must match the port that you defined in the `-p` parameter. So if the `SERVER_URL` is `http://nas:1337` then the `-p` parameter should be `-p 1337:80` (if you are not familiar with how port forwarding works in Docker, I suggest to read this first https://docs.docker.com/config/containers/container-networking/).

You can also omit the port number in the `SERVER_URL` parameter, but in that case the `-p` parameter should always `-p 80:80`.

As for accessing a Postgres instance in your host machine, instead of a Docker container, I never really tried to do that with the image that I created (I think it's something that I can test and improve in January, after the holiday season). But for now I would suggest to access your local Postgres installation using the special DNS name that points to your host machine `host.docker.internal` instead of `localhost`.

For more information see this answer on Stackoverflow: https://stackoverflow.com/a/43541732/856979

**Comment by sagerio** [comment]
Thanks for this great explanation, now I get the principle of this system!
I could also run the postgres db as a container and link to that, would simplify the thing a little bit.
I will play around with the setup and see what fits bests.

Again, thanks so much for the great work and have nice holidays, stay healthy!
